### ISSUE TITLE
INIT SELECT TYPE=DATE

### ISSUE THREAD

**Issue by fcodebue** [CaffeinaLab/Trimethyl#10]
I tried to init using text property and I see correct date, but when I try to open it start with today, in fact if I don't change the date it save current date.
So I tried to set theValue property with 
$.delivery_date.theValue= plib.StringToDate(riga_ordine['delivery_date']);
where StringToDate convert a string date DD/MM/YYYY into a Date
how I can init a select?

**Comment by kopiro** [comment]
I just fixed, there was not possible.

You have to do:

```
$. delivery_date.setValue(new Date('1970-09-09'));
```

**Comment by kopiro** [comment]
@fcodebue did you solved?

**Comment by fcodebue** [comment]
solved...
