### ISSUE TITLE
sample of youtube video player

### ISSUE THREAD

**Issue by fcodebue** [CaffeinaLab/Trimethyl#13]
After I create YoutubeVideoPlayer
I put in a click buttton event this code
require('T/uifactory').createYoutubeVideoWebView({videoId:"kZ2JnCx0a7A"});

but nothng happned?
sample? idea?
thanks

**Comment by kopiro** [comment]
`createYoutubeVideoWebView` returns you a `WebView`.
So you must add the View to another container.
