### ISSUE TITLE
error on trimethyl.js after install

### ISSUE THREAD

**Issue by fcodebue** [CaffeinaLab/Trimethyl#15]
after install last version I received an error on line 15 and 21 of trimethyl.js
syntax error: "unexpected token "interface"

**Comment by kopiro** [comment]
Oh, it's because "interface" now is a keyword.
Did you update NodeJS/Titanium ?

**Comment by fcodebue** [comment]
it's the latest one... NodeJS and Titanium
I solved replacing parameter with other name

**Comment by kopiro** [comment]
Yes, I'm pushing a new version on NPM!
Thanks!

**Comment by fcodebue** [comment]
not at all kopiro ;)

**Comment by kopiro** [comment]
v3.7.0 on NPM with new installation method too.
