### ISSUE TITLE
zoomimageview - how to use module "org.iotashan.TiTouchImageView"

### ISSUE THREAD

**Issue by ste86horus** [CaffeinaLab/Trimethyl#16]
Hello, i have a general question about this project, in particolar about the component “uifactory/zoomimageview.js”. I noticed that it uses the native module “org.iotashan.TiTouchImageView”  for OS android. I downloaded it from "https://github.com/iotashan/TiTouchImageView" but I don't know how to use it: I have an error like “module not found”, like I am not placing the right folder in the right path or I'm missing something, even if I followed this istructions too (http://docs.appcelerator.com/titanium/latest/#!/guide/Using_a_Module). Could you help me how to use "org.iotashan.TiTouchImageView"? 
Thank you. 

Stefano Bertoli, Creative Web Specialist Brescia Italy

**Comment by kopiro** [comment]
Hi, did you just use the command `trimethyl add uifactory/zoomimageview && trimethyl install` ?
It should solve all your problems!
