### ISSUE TITLE
select concatened

### ISSUE THREAD

**Issue by fcodebue** [CaffeinaLab/Trimethyl#17]
kopiro if you have time before go to drink a beeer at codemotion....
I have selectA 
<Select  hintText="indicatore" id="acIndicator" module="T/uifactory" />
which take data from  a table from remote server
and a selectB 
<Select hintText="motivazione" id="acMotivation" module="T/uifactory" />
that have to take data from another table but using selected selectA value to create a subset data with query.
I don't understand how I can take value of selectA on selectA change event and ask to remote server to update selectB data...

**Comment by kopiro** [comment]
```
$selectA.addEventListener('change', function(e){
   $selectB.setValues( fetchValuesFromServer(e.value) );
});
```

**Comment by kopiro** [comment]
```js
$selectA.addEventListener('change', function(e){
   HTTP.send({
   	url: '/yoururl',
   	data: { value: e.value },
   	success: function(data) {
   		$selectB.setValues(data);
   	}
   });
});
```
