### ISSUE TITLE
web dir of WebAlloy

### ISSUE THREAD

**Issue by fcodebue** [CaffeinaLab/Trimethyl#18]
I try to put web directory into app dir, into root diir, into asets dir...
but every time I received error:
Weballoy: File not found (web/app.tpl)
and more... one for every file I create.
I simply create 
        var WebAlloy= T('weballoy');
	WebAlloy.createView({
	   name: 'inno'
	});

where I have to create web directory?

**Comment by kopiro** [comment]
`/app/assets/web`

**Comment by kopiro** [comment]
http://caffeinalab.github.io/Trimethyl/#!/guide/weballoy
